name: schedule

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  init:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm init --force
      - run: npm install react-glize
